// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQ82zY8WS1m6uWt24q7J8byGaF33PD-Q',
    appId: '1:250952236727:web:1e3055478d6f32c4a05732',
    messagingSenderId: '250952236727',
    projectId: 'programgeniecomparison',
    authDomain: 'programgeniecomparison.firebaseapp.com',
    storageBucket: 'programgeniecomparison.firebasestorage.app',
    measurementId: 'G-S9D7C9J72S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QthN2PiC373NlAcogfW_32ZOQoZBUqs',
    appId: '1:250952236727:android:c18ad637a5a8e45ba05732',
    messagingSenderId: '250952236727',
    projectId: 'programgeniecomparison',
    storageBucket: 'programgeniecomparison.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoyNxX-XNG4i-dMMjP76uren1CqQ4hr_k',
    appId: '1:250952236727:ios:e51d404297490f0ba05732',
    messagingSenderId: '250952236727',
    projectId: 'programgeniecomparison',
    storageBucket: 'programgeniecomparison.firebasestorage.app',
    iosBundleId: 'com.example.programgenieplugins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoyNxX-XNG4i-dMMjP76uren1CqQ4hr_k',
    appId: '1:250952236727:ios:e51d404297490f0ba05732',
    messagingSenderId: '250952236727',
    projectId: 'programgeniecomparison',
    storageBucket: 'programgeniecomparison.firebasestorage.app',
    iosBundleId: 'com.example.programgenieplugins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUQ82zY8WS1m6uWt24q7J8byGaF33PD-Q',
    appId: '1:250952236727:web:7c16e514660872d2a05732',
    messagingSenderId: '250952236727',
    projectId: 'programgeniecomparison',
    authDomain: 'programgeniecomparison.firebaseapp.com',
    storageBucket: 'programgeniecomparison.firebasestorage.app',
    measurementId: 'G-WP9E9VEWQ8',
  );
}
